server:
  port: 9999 # 开发环境使用9999端口

# eureka配置
eureka:
  instance:
    hostname: yb-eureka-1 # EUREKA实例主机名，供其他应用实例精确请求的名称
    prefer-ip-address: true # 优先使用IP调用
  server:
    enableSelfPreservation: true # 保护配置，在对网络进行了分区时，此属性保证多个客户端同时或间隔很短时间内停止向eureka发送心跳后，eureka不会删除客户端，默认为true
  client: # 客户端配置
    registerWithEureka: false # 是否将这个eureka server实例注册为客户端，单中心模式不用注册，集群和HA时需要改为true
    fetchRegistry: false # 是否从eureka注册表获取注册信息
#------------------------------------------------------------------------------------------------------
# 以下是网络分区的相关配置，并不是必须的，灰度发布时需要
#------------------------------------------------------------------------------------------------------
#    region: region2 # 配置实例所在的网络分区
#    availability-zones: # 实例所在区的可用域，多个域用逗号分隔
#      region2: zone1-1,zone1-2,zone2-1,zone2-2
#------------------------------------------------------------------------------------------------------
# End
#------------------------------------------------------------------------------------------------------
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/ # 集群和HA时，在这里设置多个注册中心地址，以逗号分隔
#------------------------------------------------------------------------------------------------------
# 如果设置了网络分区，service-url还需要逐个配置可用域的地址
#------------------------------------------------------------------------------------------------------
#      zone1-1: http://
#      zone1-2: http://
#      zone2-1: http://
#      zone2-2: http://

log-path: "/Users/liuwei/log/yb"
log-level: debug